authentication/urls.py
from django.urls import path, include

from . import views

app_name = 'authentication'
urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

lab_4/urls.py
from django.urls import path

from . import views

app_name = 'lab_4'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail', views.detail, name='detail'),
    path('register', views.register, name='register'),
    path('schedule', views.schedule, name='schedule'),
    path('schedule/delete_all', views.schedule_delete_all, name='schedule_delete_all')
]

lab_6/urls.py
from django.urls import path

from . import views

app_name = 'lab_6'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.profile, name='profile'),
    path('message/<int:message_id>/delete', views.delete, name='delete'),
]

lab_9/urls.py
from django.urls import path, include, re_path
from django.contrib.auth import views

from . import views as lab9_view

app_name = 'lab_9'
urlpatterns = [
    path('', lab9_view.index, name='index'),
    path('register', lab9_view.register, name='register'),
    path('subscribers', lab9_view.subscribers, name='subscribers'),
    path('api/validate_email', lab9_view.api_validate_email, name='api_validate_email'),
    path('api/register', lab9_view.api_register, name='api_register'),
    path('api/update_counter', lab9_view.update_counter, name='update_counter'),
]

ppw/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from lab_9.views import index

urlpatterns = [
    path('', index, name='index'),
    path('lab_4/', include('lab_4.urls')),
    path('lab_6/', include('lab_6.urls')),
    path('lab_9/', include('lab_9.urls')),
    path('authentication/', include('authentication.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
]

# urlpatterns += [
#     path('accounts/', include('django.contrib.auth.urls')),
# ]

lab_9/models.py
from django.db import models

class Subscriber(models.Model):
  name = models.CharField(max_length=40)
  email = models.EmailField(max_length=40, unique=True)
  password = models.CharField(max_length=40)

  def get_email(self):
    return self.email

  def __str__(self):
    return self.email

lab_9/forms.py
from django import forms

class SubscribeForm(forms.Form):
  name = forms.CharField(max_length=40, widget=forms.TextInput(attrs={
    'class': 'form-control',
  }))
  email = forms.EmailField(widget=forms.EmailInput(attrs={
    'class': 'form-control',
  }))
  password = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={
    'class': 'form-control',
  }))

lab_9/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers

from .forms import SubscribeForm
from .models import Subscriber

def index(request):
  return render(request, 'lab_9/index.html')

def register(request):
  if request.method == 'GET':
    form = SubscribeForm()

    return render(request, 'lab_9/register.html', {'form': form})
  else:
    form = SubscribeForm(request.POST)
    if form.is_valid():
      cleaned_data = form.cleaned_data
      new_subscriber = Subscriber(name=cleaned_data['name'], email=cleaned_data['email'], password=cleaned_data['password'])
      new_subscriber.save()
    else:
      return HttpResponse('invalid')
    return HttpResponseRedirect(reverse('lab_9:register'))

def subscribers(request):
  data = Subscriber.objects.values_list('name', 'email')
  return render(request, 'lab_9/subscribers.html', {'data': data})

def api_validate_email(request):
  email = request.GET.get('q', None)
  data = [ obj.get_email() for obj in Subscriber.objects.all() ]
  if email == None or email in data:
    return JsonResponse({'valid': False})
  else:
    return JsonResponse({'valid': True})

def api_register(request):
  if (request.method == 'POST'):
    form = SubscribeForm(request.POST)
    if (form.is_valid()):
      name = form.cleaned_data['name']
      email = form.cleaned_data['email']
      password = form.cleaned_data['password']
      new_sub = Subscriber(name=name, email=email, password=password)
      new_sub.save()
      return JsonResponse({'success': True})
    return JsonResponse({'success': False})

def update_counter(request):
  if request.user.is_authenticated:
    if request.session.get('favourite_counter', None) == None:
      request.session['favourite_counter'] = 1
    else:
      if request.GET.get('q', None) == 'increment':
        request.session['favourite_counter'] += 1
      elif request.GET.get('q', None) == 'decrement':
        request.session['favourite_counter'] -= 1
    return JsonResponse({'success': True, 'counter': request.session.get('favourite_counter', None), 'q': request.POST.get('q')})
  return JsonResponse({'success': False})

templates/lab_9/_base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- bootstrap css -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
      {% block css %}{% endblock %}

      <!-- fontawseom icons -->
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
      {% block font %}{% endblock %}

      <title>{% block title %}{% endblock %}</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'lab_9:index' %}">Nicolaus</a>
      
      <ul class="navbar-nav flex-grow-1 flex-row-reverse">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Previous Stories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'lab_4:index' %}">story4-5</a>
            <a class="dropdown-item" href="{% url 'lab_6:index' %}">story6-8</a>
          </div>
        </li>
      </ul>
    </nav>

    {% block content %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
      crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
  </body>
</html>

templates/lab_9/index.html
{% extends 'lab_9/_base.html' %}
{% load static %}

{% block title %}Nicolaus | Story 9 Books{% endblock %}
{% block css %}
  <link type="text/css" rel="stylesheet" href="{% static 'lab_9/index/style.css' %}">
{% endblock %}
{% block script %}
  <script src="{% static 'lab_9/index/script.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container">
  <h1 class="display-1">BOOKS</h1>

  <a type="button" class="btn btn-dark" href="{% url 'lab_9:register' %}">Subscribe to newsletter</a>
  <a type="button" class="btn btn-dark" href="{% url 'lab_9:subscribers' %}">View subscribers</a>
  {% if request.user.is_authenticated %}
    <div class="btn btn-light">Hi {{ request.user }}!</div>
    <a type="button" class="btn btn-light" href="{% url 'authentication:logout' %}">Logout</a>
  {% else %}
    <a type="button" class="btn btn-light" href="{% url 'authentication:login' %}">Login</a>
  {% endif %}
  <h1 class="display-4">Favourites: <span id="counter">-</span></h1>
  <p class="lead session-info">Session Fav: <span id="session-counter">-</span></p>
  <div class="search-form row justify-content-center">
    <div class="col-7 col-md-5">
      <input type="text" class="form-control" id="search-query" placeholder="search something">
    </div>
    <div class="col-1 col-md-1">
      <button id="submit-button">submit</button>
    </div>
  </div>

  <table id="books" class="table">
    <thead>
      <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Short description</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td colspan="3"><div class="loader"></div></td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

templates/lab_9/register.html
{% extends 'lab_9/_base.html' %}
{% load static %}

{% block title %}Nicolaus | Story 10 Subscribe{% endblock %}
{% block script %}<script src="{% static 'lab_9/register/script.js' %}"></script>{% endblock %}
{% block content %}
<div class="container">
  <h1>Register</h1>
  <p id="message"></p>
  <form action="{% url 'lab_9:register' %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div class="form-group">
      {{ form.name.errors }}
      <label for="{{ form.name.id_for_label }}">Name:</label>
      {{ form.name }}
      <div class="invalid-feedback">
        Name cannot be empty
      </div>
    </div>
    <div class="form-group">
      {{ form.email.errors }}
      <label for="{{ form.email.id_for_label }}">Email:</label>
      {{ form.email }}
      <div class="invalid-feedback">
        Must be a valid email
      </div>
    </div>
    <div class="form-group">
      {{ form.password.errors }}
      <label for="{{ form.password.id_for_label }}">Password:</label>
      {{ form.password }}
      <div class="invalid-feedback">
        Password cannot be empty
      </div>
    </div>
    <button id="register-button" class="btn waves-effect waves-light black" type="submit" name="action" disabled>Register</button>
  </form>
</div>

{% endblock %}

templates/lab_9/subscribers.html
{% extends 'lab_9/_base.html' %}
{% load static %}

{% block title %}Nicolaus | Story 10 Subscribers{% endblock %}

{% block content %}
<div class="container">
  <h1>Subscriber list</h1>

  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      {% for name, email in data %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>{{ name }}</td>
          <td>{{ email }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}