lab_6/urls.py
from django.urls import path

from . import views

app_name = 'lab_6'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.profile, name='profile'),
    path('message/<int:message_id>/delete', views.delete, name='delete'),
]

ppw/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from lab_9.views import index

urlpatterns = [
    path('', index, name='index'),
    path('lab_4/', include('lab_4.urls')),
    path('lab_6/', include('lab_6.urls')),
    path('lab_9/', include('lab_9.urls')),
    path('authentication/', include('authentication.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
]

# urlpatterns += [
#     path('accounts/', include('django.contrib.auth.urls')),
# ]

lab_6/models.py
from django.db import models

class Message(models.Model):
    message = models.CharField(max_length=100)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message

lab_6/forms.py
from django import forms

class MessageForm(forms.Form):
    message = forms.CharField(max_length=100, widget=forms.Textarea(attrs={
        'id': 'message-form-message',
        'class': 'form-control',
        'placeholder':'message',
        'rows': '3',
    }))

lab_6/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect

from .models import Message
from .forms import MessageForm

def index(request):
    if request.method == 'GET':
        form = MessageForm()
        messages = Message.objects.all()

        return render(request, 'lab_6/index.html', {'messages': messages, 'form': form})
    else:
        form = MessageForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            new_message = Message(message=cleaned_data['message'])
            new_message.save()

            return HttpResponseRedirect('./')

def delete(request, message_id):
    message = get_object_or_404(Message, pk=message_id)
    message.delete()

    return HttpResponseRedirect('../../')

def profile(request):
    return render(request, 'lab_6/profile.html')

templates/lab_6/index.html
<!DOCTYPE html> {% load static %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'lab_6/style.css' %}">

    <title>Nicolaus</title>
</head>

<body>
    <div class="loader"></div>

    <div class="container animate-bottom">
        <div class="row justify-content-center">
            <div class="col-12">
                <h1 class="display-1">Hello, how are you?</h1>
                <p>
                    <button id="update-button" class="btn bg-dark text-light" type="button" data-toggle="collapse" data-target="#messageFormCollapse" aria-expanded="false"
                        aria-controls="messageFormCollapse">
                        Give an update of yourself
                    </button>
                    <a class="btn bg-dark text-light" href="{% url 'lab_6:profile' %}">
                        See profile
                    </a>
                    <a class="btn bg-dark text-light" id="change-theme-button">
                        Change theme
                    </a>
                </p>
                <div class="collapse" id="messageFormCollapse">
                    <div class="card card-body">

                        <form action="{% url 'lab_6:index' %}" method="post" id="message-form">
                            {% csrf_token %} {{ form.non_field_errors }}
                            <div class="form-group">
                                {{ form.message.errors }}
                                {{ form.message }}
                            </div>
                            <div>
                                <button id="submit-button" type="submit" name="action">
                                    submit
                                </button>
                            </div>
                        </form>
                    </div>
                </div>

                {% for message in messages %}
                <!-- <div class="card bg-light mb-3" style="max-width: 18rem;"> -->
                <div class="card bg-light mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Nicolaus
                            <span class="message-card-date">{{ message.created_at|date:"F d H:i" }}</span>
                        </h5>
                        <p class="card-text">{{ message.message }}</p>
                        <a id="delete-status" class="text-warning message-card-delete" href="{% url 'lab_6:delete' message.id %}">delete</a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="{% static 'lab_6/script.js' %}"></script>
</body>

</html>

templates/lab_6/profile.html
<!DOCTYPE html> {% load static %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <link type="text/css" rel="stylesheet" href="{% static 'lab_6/style.css' %}">

    <title>Nicolaus</title>
</head>

<body>
    <div class="loader"></div>

    <div class="container animate-bottom">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="jumbotron bg-dark text-light">
                    <h1 class="display-4">Nicolaus C</h1>
                    <p class="lead">A second year computer science student.</p>
                    <a class="btn bg-light text-dark" href="{% url 'index' %}" role="button">Get back and send me an update</a>
                    <a class="btn bg-light text-dark" id="change-theme-button">
                        Change theme
                    </a>
                </div>
            </div>
        </div>

        <div class="accordion">
            <div class="accordion__item">
                <button class="accordion__head">Activities</button>
                <div class="accordion__body">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque dictum nisl ac neque porttitor ultricies. Suspendisse potenti. Integer mollis, dolor in commodo molestie, nulla ligula lobortis velit, eget mollis odio ipsum nec nisi. Suspendisse eu sapien nunc.
                    </p>
                </div>
            </div>
            <div class="accordion__item">
                <button class="accordion__head">Experience</button>
                <div class="accordion__body">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque dictum nisl ac neque porttitor ultricies. Suspendisse potenti. Integer mollis, dolor in commodo molestie, nulla ligula lobortis velit, eget mollis odio ipsum nec nisi. Suspendisse eu sapien nunc.
                    </p>
                </div>
            </div>
            <div class="accordion__item">
                <button class="accordion__head">Achievements</button>
                <div class="accordion__body">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque dictum nisl ac neque porttitor ultricies. Suspendisse potenti. Integer mollis, dolor in commodo molestie, nulla ligula lobortis velit, eget mollis odio ipsum nec nisi. Suspendisse eu sapien nunc.
                    </p>
                </div>
            </div>
        </div>

    </div>


    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
    <script src="{% static 'lab_6/script.js' %}"></script>
</body>

</html>