lab_4/urls.py
from django.urls import path

from . import views

app_name = 'lab_4'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail', views.detail, name='detail'),
    path('register', views.register, name='register'),
    path('schedule', views.schedule, name='schedule'),
    path('schedule/delete_all', views.schedule_delete_all, name='schedule_delete_all')
]

ppw/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from lab_9.views import index

urlpatterns = [
    path('', index, name='index'),
    path('lab_4/', include('lab_4.urls')),
    path('lab_6/', include('lab_6.urls')),
    path('lab_9/', include('lab_9.urls')),
    path('authentication/', include('authentication.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^auth/', include('social_django.urls', namespace='social')),
]

# urlpatterns += [
#     path('accounts/', include('django.contrib.auth.urls')),
# ]

lab_4/models.py
from django.db import models

class Activity(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    date_time = models.DateTimeField()
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

lab_4/forms.py
from django import forms

class ActivityForm(forms.Form):
    name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'id': 'activity-name'}))
    location = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'id': 'activity-location'}))
    category = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'id': 'activity-category'}))
    date_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'id': 'activity-date_time'}))

lab_4/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages

from .models import Activity
from .forms import ActivityForm

def index(request):
    return render(request, 'lab_4/index.html')

def detail(request):
    return render(request, 'lab_4/detail.html')
    
def register(request):
    if request.method == 'GET':
        return render(request, 'lab_4/register.html')
    else:
        messages.success(request, "Your form has been submitted! Well not really..")
        return HttpResponseRedirect('register')

def schedule(request):
    if request.method == 'GET':
        show_activity_count = 10
        form = ActivityForm()
        if Activity.objects.all().count() >= show_activity_count:
            activities = (Activity.objects.order_by('-date_time')[:show_activity_count])[::-1]
        else:
            activities = (Activity.objects.order_by('-date_time'))[::-1]
        
        return render(request, 'lab_4/schedule.html', { 'activities': activities, 'form': form })
    else:
        form = ActivityForm(request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            new_activity = Activity(name=cleaned_data['name'], location=cleaned_data['location'], category=cleaned_data['category'], date_time=cleaned_data['date_time'])
            new_activity.save()
            return HttpResponseRedirect('schedule')
        else:
            messages.error(request, 'your form submission invalid :(')
            return HttpResponseRedirect('schedule')

def schedule_delete_all(request):
    if request.method == 'POST':
        info = Activity.objects.all().delete()
        messages.success(request, 'successfully deleted {:d} activity(s) :)'.format(info[0]))
        return HttpResponseRedirect('../schedule')
    else:
        messages.error(request, 'sorry the previous page is POST only')
        return HttpResponseRedirect('../schedule')

templates/lab_4/_base.html
<!DOCTYPE html>

{% load static %}

<html>
    <head>
        <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        <!-- materialize css and custom css -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
        <link type="text/css" rel="stylesheet" href="{% static 'lab_4/css/style.css' %}">

        <title>{% block title %}{% endblock %}</title>
    </head>
    
    <body>
        {% block content %}{% endblock %}

        <!--JavaScript at end of body for optimized loading-->    
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
        <script src="{% static 'lab_4/js/script.js' %}"></script>
    </body>
</html>

templates/lab_4/_contact.html
{% load static %}

<section id="contact" class="section scrollspy">
    <div class="contact black">
        <div class="row">
            <div class="col s12 white-text">
                <div class="contact-card">
                    <h1>Contact</h1>
                    <p class="quote">Let’s build something amazing together!</p>
                    <div class="col s12 l4">
                        <a href="https://www.github.com/nicolauscg" target="_blank">
                            <div class="icon">
                                <img src="{% static 'lab_4/img/002-cat.png' %}">
                            </div>
                            <span class="text">github.com/nicolauscg</span>
                        </a>
                    </div>
                    <div class="col s12 l4">
                        <a href="https://www.linkedin.com/in/nicolauscg" target="_blank">
                            <div class="icon">
                                <img src="{% static 'lab_4/img/003-linkedin.png' %}">
                            </div>
                            <span class="text">linkedin.com/in/nicolauscg</span>
                        </a>
                    </div>
                    <div class="col s12 l4">
                        <a href="mailto:nicolauscg@gmail.com" target="_blank">
                            <div class="icon">
                                <img src="{% static 'lab_4/img/001-mail.png' %}">
                            </div>
                            <span class="text">nicolauscg@gmail.com</span>
                        </a>
                    </div>
                    <div class="col s12">
                        <div class="symbol-name">
                            <p>
                                <span class="copy-left">&copy;</span>2018 Nicolaus</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/lab_4/detail.html
{% extends 'lab_4/_base.html' %}
{% load static %}

{% block title %}Project detail{% endblock %}

{% block content %}
    <!-- navbar -->
    <div class="custom-wrapper">
        <nav class="navbar">
            <div class="nav-wrapper white black-text">
                <span class="brand-logo black-text">N</span>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons black-text">menu</i></a>
                <ul class="right hide-on-med-and-down section table-of-contents">
                    <li><a href="{% url 'lab_4:index' %}#project">Return to Projects</a></li>
                </ul>
            </div>
        </nav>
    </div>
    <ul class="side-nav" id="mobile-demo">
        <li><a href="{% url 'lab_4:index' %}#project">Return to Projects</a></li>
    </ul>

    <div class="row">
        <div class="col s12 m10 l8 push-m1 push-l2">
            <div class="detail-title">
                <h1>Circular</h1>
                <p>Web content rating and discussion website . Sep 2018</p>
                <div class="divider"></div>
            </div>
            <div class="detial-content">
                <p>Role : Front End Developer</p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam dolor erat, 
                    consequat in rutrum quis, auctor non lacus. Etiam sollicitudin tincidunt placerat
                </p>
                <div class="interest">
                    <a href="https://ppwki.ajardia.com" target="_blank">
                        <div class="clickable">
                            <div class="icon"><img src="{% static 'lab_4/img/004-pin.png' %}"></div>
                            <span class="text">visit site</span>
                        </div>
                    </a>
                </div>
                <img src="{% static 'lab_4/img/circular.jpg' %}" alt="screenshot">
            </div>
            <div class="empty-div"></div>
        </div>
    </div>

    <!-- contact section -->
    {% include "lab_4/_contact.html" %}
{% endblock %}

templates/lab_4/index.html
{% extends 'lab_4/_base.html' %}
{% load static %}

{% block title %}Nic's Portfolio{% endblock %}

{% block content %}
    <!-- landing page -->
    <section id="top">
        <div class="landing-page">
            <div class="name">
                <h1>Nicolaus Christian Gozali</h1>
            </div>
            <div class="down-arrow">
                <a href="#profile"><img src="{% static 'lab_4/img/down-arrow.png' %}"></a>
            </div>
        </div>
    </section>
    
    <!-- navbar -->
    <div class="custom-wrapper">
        <nav class="navbar">
            <div class="nav-wrapper white black-text">
                <span class="brand-logo black-text">N</span>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons black-text">menu</i></a>
                <ul class="right hide-on-med-and-down section table-of-contents">
                    <li><a href="#profile">Profile</a></li>
                    <li><a href="#experience">Experience</a></li>
                    <li><a href="#project">Project</a></li>
                    <li><a href="#contact">Contact</a></li>
                    <li><a href="{% url 'lab_4:schedule' %}">Schedule</a></li>
                    <li><a href="{% url 'lab_4:register' %}">Register</a></li>
                </ul>
            </div>
        </nav>
    </div>
    <ul class="side-nav" id="mobile-demo">
        <li><a href="#profile">Profile</a></li>
        <li><a href="#experience">Experience</a></li>
        <li><a href="#project">Project</a></li>
        <li><a href="#contact">Contact</a></li>
        <li><a href="{% url 'lab_4:schedule' %}">Schedule</a></li>
        <li><a href="{% url 'lab_4:register' %}">Register</a></li>
    </ul>

    <!-- profile section -->
    <section id="profile" class="section scrollspy"> 
        <div class="empty-div"></div>
        <div class="row">
            <div class="col s12 m10 l8 push-m1 push-l2">
                <h1>Profile</h1>
                <h2>I'm a CS student at UI</h2>
                <div class="divider"></div>
            </div>
        </div>
        <div class="row">
            <div class="col s12 m10 l8 push-m1 push-l2">
                <div class="col s12 l4">
                    <h3>A little about myself</h3>
                    <p>
                        Hi, I am Nicolaus and I am currently at my second year here in UI. Throughout the year, making web applications and finding patterns in data piqued my interest. 
                        Although I may have just scratched the surface, I am eager to learn and dwelve deeper on this ever evolving field.
                    </p>
                </div>
                <div class="col s12 l4">
                    <div class="profile-pic"><img src="{% static 'lab_4/img/prof.png' %}"></div>
                </div>
                <div class="col s12 l4">
                    <h3>Interests</h3>
                    <div class="interest">
                        <div class="icon"><img src="{% static 'lab_4/img/001-web.png' %}"></div>
                        <span class="text">Web Development</span>
                    </div>
                    <div class="interest">
                        <span class="icon"><img src="{% static 'lab_4/img/002-analysis.png' %}"></span>
                        <span class="text">Data Science</span>
                    </div>
                    <div class="interest">
                        <span class="icon"><img src="{% static 'lab_4/img/003-console.png' %}"></span>
                        <span class="text">Games</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="empty-div"></div>
    </section>

    <!-- experience section -->
    <section id="experience" class="section scrollspy"> 
        <div class="row">
            <div class="col s12 m10 l8 push-m1 push-l2">
                <h1>Experience</h1>
                <div class="divider"></div>
                <h3>Education</h3>
                <div class="card">
                    <div class="card-content custom-experience-card-content black-text">
                        <div class="col s12 l4">
                            <span class="card-title">Universitas Indonesia</span>
                            <span class="experience-card-date">May 2017 - now</span>
                        </div>
                        <div class="col s12 l8">
                            <span class="experience-card-heading">Bachelor - Computer Science</span>
                            <p>I'm currently in my second year here and the education is mainly java-based programming. I am interested to pursue a data science major next year.</p>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-content custom-experience-card-content black-text">
                        <div class="col s12 l4">
                            <span class="card-title">GO-ACADEMY</span>
                            <span class="experience-card-date">Jul 2018 - Aug 2018</span>
                        </div>
                        <div class="col s12 l8">
                            <span class="experience-card-heading">Participant - GOJEKxCompfest Software Engineering Academy</span>
                            <p>6 day bootcamp over 3 weeks, tutored by engineers from Gojek. Learnt about clean code, TDD, microservices and engineering cultures in the industry.</p>
                        </div>
                    </div>
                </div>
                <div class="divider"></div>
                <h3>Career</h3>
                <div class="card">
                    <div class="card-content custom-experience-card-content black-text">
                        <div class="col s12 l4">
                            <span class="card-title">Universitas Indonesia</span>
                            <span class="card-date">Sep 2018 - now</span>
                        </div>
                        <div class="col s12 l8">
                            <span class="experience-card-heading">Teaching Assistant - Programming Foundations 1</span>
                            <p>An intoductory python course attended by 29 students. Grades assignments, provide demo session and watch over lab session</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="empty-div"></div>
    </section>
    
    <!-- featured projects section -->
    <section id="project" class="section scrollspy"> 
        <div class="row">
            <div class="col s12 m10 l8 push-m1 push-l2">
                <h1>Featured Projects</h1>
                <div class="divider"></div>
                <div class="col s12 m4">
                    <div class="card project-card medium">
                        <div class="card-image">
                            <img src="{% static 'lab_4/img/circular.jpg' %}">                          
                        </div>
                        <div class="card-content">
                            <span class="card-title black-text">Circular</span>
                            <p>Web content rating and discussion website</p>
                        </div>
                        <div class="card-action">
                            <span class="date">Sep 2018</span>
                            <a href="{% url 'lab_4:detail' %}" class="black-text">view details</a>
                        </div>
                    </div>
                </div>
                <div class="col s12 m4">
                        <div class="card project-card medium">
                            <div class="card-image">
                                <img src="{% static 'lab_4/img/kurnia.png' %}">                            
                            </div>
                            <div class="card-content">
                                <span class="card-title black-text">Kurnia</span>
                                <p>Highschool website</p>
                            </div>
                            <div class="card-action">
                                <span class="date">Sep 2018</span>
                                <a href="{% url 'lab_4:detail' %}" class="black-text">view details</a>
                            </div>
                        </div>
                </div>
                <div class="col s12 m4">
                    <div class="card project-card medium">
                        <div class="card-image">
                            <img src="{% static 'lab_4/img/question-mark.png' %}">
                        </div>
                        <div class="card-content">
                            <span class="card-title black-text">And more to come!</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="empty-div"></div>
    </section>

    <!-- contact section -->
    {% include "lab_4/_contact.html" %}
{% endblock %}

templates/lab_4/register.html
{% extends 'lab_4/_base.html' %}
{% load static %}

{% block title %}Register{% endblock %}

{% block content %}
    <!-- navbar -->
    <div class="custom-wrapper">
        <nav class="navbar">
            <div class="nav-wrapper white black-text">
                <span class="brand-logo black-text">N</span>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons black-text">menu</i></a>
                <ul class="right hide-on-med-and-down section table-of-contents">
                    <li><a href="{% url 'lab_4:index' %}#profile">Return to Profile</a></li>
                </ul>
            </div>
        </nav>
    </div>
          
    {% if messages %}
        <div id="modal1" class="modal">
            <div class="modal-content">
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="modal-footer">
                <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
            </div>
        </div>
    {% endif %}

    <ul class="side-nav" id="mobile-demo">
        <li><a href="{% url 'lab_4:index' %}#profile">Return to Profile</a></li>
    </ul>
        
    <div class="register-menu black-text">
        <div class="row">
            <div class="col s12 m10 l8 push-m1 push-l2">
                <h1>Register</h1>
            </div>
        </div>
        <div class="row">
            <form class="col s12 m10 l8 push-m1 push-l2" action="{% url 'lab_4:register' %}" method="post"  id="register-form">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s12">
                        <input id="full_name" type="text" class="validate" required="" aria-required="true">
                        <label for="full_name">Full Name</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <input id="username" type="text" class="validate" required="" aria-required="true">
                        <label for="username">Username</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <input id="email" type="email" class="validate" required="" aria-required="true">
                        <label for="email">Email</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m6">
                        <input id="password" type="password" class="validate" required="" aria-required="true">
                        <label for="password">Password</label>
                    </div>
                    <div class="input-field col s12 m6">
                        <input id="passwordConfirm" type="password" required="" aria-required="true">
                        <label id="lblPasswordConfirm" for="passwordConfirm" data-error="Password not match" data-success="Password Match">Password (Confirm)</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12 m6">
                        <input type="text" id="birthdate" class="datepicker picker__input" required>
                        <label for="birthdate">Birthdate</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <button class="btn waves-effect waves-light black" type="submit" name="action">
                            Submit<i class="material-icons right">send</i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/lab_4/schedule.html
{% extends 'lab_4/_base.html' %}
{% load static %}

{% block title %}Personal Schedule{% endblock %}
{% block content %}
    <div class="custom-wrapper">
        <nav class="navbar">
            <div class="nav-wrapper white black-text">
                <span class="brand-logo black-text">N</span>
                <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons black-text">menu</i></a>
                <ul class="right hide-on-med-and-down section table-of-contents">
                    <li><a href="{% url 'lab_4:index' %}#profile">Return to Profile</a></li>
                </ul>
            </div>
        </nav>
    </div>
    <ul class="side-nav" id="mobile-demo">
        <li><a href="{% url 'lab_4:index' %}#profile">Return to Profile</a></li>
    </ul>
    <h1>Personal Schedule</h1>

    {% if messages %}
        <div id="modal1" class="modal">
            <div class="modal-content">
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="modal-footer">
                <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
            </div>
        </div>
    {% endif %}

    {% if activities|length > 0 %}
        {% for activity in activities %}
            <div class="row">
                <div class="col s12 m10 l8 push-m1 push-l2">
                    <div class="card-panel activity-card white">
                        <div class="activity-date">
                            <div>{{ activity.date_time | date:"F d"}}</div>
                            <div class="date-text">{{ activity.date_time | time:"H:i"}}</div>
                        </div>
                        <div class="activity-content">
                            <div class="activity-title">{{ activity.name }}</div>
                            <span class="activity-category">{{ activity.category }}</span>
                            <span class="activity-location"><img class="icon" src="{% static 'lab_4/img/004-pin.png' %}">{{ activity.location }}</span>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
            <div class="row">
                <div class="col s12 m10 l8 push-m1 push-l2">
                    <div class="card-panel activity-card white">
                        no activities yet
                    </div>
                </div>
            </div>
    {% endif %}

    <div class="row">
        <div class="col s12 m10 l8 push-m1 push-l2">
            <a class="waves-effect waves-light btn modal-trigger black right" href="#modal2">Add new activity</a>
            
            <form action="{% url 'lab_4:schedule_delete_all' %}" method="post">
                {% csrf_token %}
                <button class="btn waves-effect waves-light black" type="submit" name="action">
                    Complete All
                </button>
            </form>

            <!-- Modal Structure -->
            <div id="modal2" class="modal">
                <div class="modal-content">
                    <h3>New activity</h3>

                    <form action="{% url 'lab_4:schedule' %}" method="post" id="activity-form">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div class="input-field">
                            {{ form.name.errors }}
                            <label for="{{ form.name.id_for_label }}">Name</label>
                            {{ form.name }}
                        </div>
                        <div class="input-field">
                            <label for="{{ form.location.id_for_label }}">Location</label>
                            {{ form.location }}
                        </div>
                        <div class="input-field">
                            <label for="{{ category.id_for_label }}">Category</label>
                            {{ form.category }}
                        </div>
                        <div class="input-field">
                            <label for="{{ date.id_for_label }}">Date and Time (yyyy-MM-dd hh:mm)</label>
                            {{ form.date_time }}
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <button class="btn waves-effect waves-light black" type="submit" name="action">
                                    Submit<i class="material-icons right">send</i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="empty-div"></div>
        </div>
    </div>
{% endblock %}